---
# Name your file secrets.yml

development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  BINANCE_API_SECRET: create_your_binance_api
  BINANCE_API_KEY: create_your_binance_api
  SESSION_SECRET: ""
  TG_API_ID: create_tg_api
  TG_API_HASH: create_tg_api
  TG_PHONE: create_tg_api
  TG_USERNAME: create_tg_api
  APP_HOST: http://localhost:9292

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  BINANCE_API_SECRET: create_your_binance_api
  BINANCE_API_KEY: create_your_binance_api
  SESSION_SECRET: ""
  TG_API_ID: create_tg_api
  TG_API_HASH: create_tg_api
  TG_PHONE: create_tg_api
  TG_USERNAME: create_tg_api
  APP_HOST: http://localhost:9292

app_test:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore
  # Application
  BINANCE_API_SECRET: create_your_binance_api
  BINANCE_API_KEY: create_your_binance_api
  SESSION_SECRET: ""
  TG_API_ID: create_tg_api
  TG_API_HASH: create_tg_api
  TG_PHONE: create_tg_api
  TG_USERNAME: create_tg_api
  APP_HOST: http://localhost:9292

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  GITHUB_TOKEN: create_github_token
  BINANCE_API_SECRET: create_your_binance_api
  BINANCE_API_KEY: create_your_binance_api
  SESSION_SECRET: ""
  TG_API_ID: create_tg_api
  TG_API_HASH: create_tg_api
  TG_PHONE: create_tg_api
  TG_USERNAME: create_tg_api
  APP_HOST: http://localhost:9292
