---
# Name your file secrets.yml

development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  BINANCE_API_SECRET: create_your_binance_api
  BINANCE_API_KEY: create_your_binance_api
  SESSION_SECRET: ""
  TG_API_ID: create_tg_api
  TG_API_HASH: create_tg_api
  TG_PHONE: create_tg_api
  TG_USERNAME: create_tg_api

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  BINANCE_API_SECRET: create_your_binance_api
  BINANCE_API_KEY: create_your_binance_api
  SESSION_SECRET: ""
  TG_API_ID: create_tg_api
  TG_API_HASH: create_tg_api
  TG_PHONE: create_tg_api
  TG_USERNAME: create_tg_api
